### ISSUE TITLE
latest version from 26-July was not able to start

### ISSUE THREAD

**Issue by computrade** [aaronshaf/dynamodb-admin#137]
Tag:
aaronshaf/dynamodb-admin:latest
DIGEST:sha256:568bb40d291be2f604e63dc54392dc2389317b5898c19610a79793f847ec723f

This is the docker logs:

/node_modules/argparse/argparse.js:222
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/bin/dynamodb-admin.js:3:28)
/node_modules/argparse/argparse.js:222
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/bin/dynamodb-admin.js:3:28)
/node_modules/argparse/argparse.js:222
    } catch {}
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/bin/dynamodb-admin.js:3:28)

**Comment by rchl** [comment]
It looks like updated dependencies require never node version than what is currently used.

@aaronshaf can we bump up node version to v12 at least? I don't have access to the docker part.

**Comment by rchl** [comment]
I've realized that the docker image is built based of `Dockerfile` in this repo so it should be fixed now.

@aaronshaf unrelated to this issue, there seems to be images being built for all PRs also which seems unnecessary - https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags?page=1&ordering=last_updated
