### ISSUE TITLE
Problem installing globally by npm, "Error: EACCES: permission denied, open '/Users/zervis/.config/configstore/bower-github.json' You don't have access to this file."

### ISSUE THREAD

**Issue by tareq89** [aaronshaf/dynamodb-admin#21]
```
> dynamodb-admin@1.14.0 postinstall /usr/local/lib/node_modules/dynamodb-admin
> bower install

/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/zervis/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.get (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamodb-admin@1.14.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamodb-admin@1.14.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zervis/.npm/_logs/2017-09-12T09_40_21_639Z-debug.log
```

Previously I installed this npm package without any problem. But recently it is giving me this error. I have tried to install this package in multiple mac, one being a freshly installed OS. But still the same error.
I have searched for this problem. Found this : https://github.com/bower/bower/issues/2262
In this link, people suggested to do this:
```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```
But this doesn't solve the problem. Can anyone help how this problem can be fixed?

**Comment by MatheusVellone** [comment]
What ouput `ll ~/.config/configstore/bower-github.json` gives you ?

**Comment by tareq89** [comment]
@MatheusVellone thanks for asking, just an empty js object. {}

**Comment by MatheusVellone** [comment]
@tareq89, I guess you ran the `cat` command instead of the `ll`.
But I've checked my `cat` output, and it is the same I get here on my debian.
Reading the issue in bower you mentioned, this looks like a permission error, and the command you tried should set correct permissions recursively on those directories.
Double check your `~/.config/configstore/bower-github.json` file permission with the `ll` command on the file. Looks like the error happens beacuse the system can't access this file.

To use as base, my output for the `ll` command: `-rw------- 1 matheus matheus 2 Sep  9 18:09 /home/matheus/.config/configstore/bower-github.json`. I guess your's must be something like mine.

Can't help you too much on this, sorry.

**Comment by tareq89** [comment]
```
Muhammeds-Mac-mini:configstore zervis$ sudo npm install -g dynamodb-admin
/usr/local/bin/dynamodb-admin -> /usr/local/lib/node_modules/dynamodb-admin/bin/dynamodb-admin.js

> dynamodb-admin@1.14.0 postinstall /usr/local/lib/node_modules/dynamodb-admin
> bower install

/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:70
				throw err;
				^

Error: EACCES: permission denied, open '/Users/zervis/.config/configstore/bower-github.json.2606134293'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1348:33)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/write-file-atomic/index.js:78:8)
    at Object.set (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:63:21)
    at Object.Configstore (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/node_modules/configstore/index.js:28:11)
    at readCachedConfig (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/dynamodb-admin/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dynamodb-admin@1.14.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dynamodb-admin@1.14.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zervis/.npm/_logs/2017-09-19T10_03_21_519Z-debug.log
Muhammeds-Mac-mini:configstore zervis$ ll ~/.config/configstore/bower-github.json
-bash: ll: command not found
Muhammeds-Mac-mini:configstore zervis$ less /Users/zervis/.npm/_logs/2017-09-19T10_03_21_519Z-debug.log

2145 verbose stack     at emitTwo (events.js:106:13)
2145 verbose stack     at EventEmitter.emit (events.js:191:7)
2145 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2145 verbose stack     at emitTwo (events.js:106:13)
2145 verbose stack     at ChildProcess.emit (events.js:191:7)
2145 verbose stack     at maybeClose (internal/child_process.js:920:16)
2145 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
2146 verbose pkgid dynamodb-admin@1.14.0
2147 verbose cwd /Users/zervis/.config/configstore
2148 verbose Darwin 16.7.0
2149 verbose argv "/usr/local/Cellar/node@6/6.11.3/bin/node" "/usr/local/bin/npm" "install" "-g" "dynamodb-admin"
2150 verbose node v6.11.3
2151 verbose npm  v5.4.2
2152 error code ELIFECYCLE
2153 error errno 1
2154 error dynamodb-admin@1.14.0 postinstall: `bower install`
2154 error Exit status 1
2155 error Failed at the dynamodb-admin@1.14.0 postinstall script.
2155 error This is probably not a problem with npm. There is likely additional logging output above.
2156 verbose exit [ 1, true ]
```

**Comment by MatheusVellone** [comment]
Mac-os doesn't have `ll` command out of box.
Try `ls -al ~/.config/configstore/bower-github.json` instead

**Comment by tareq89** [comment]
```
ls -la ~/.config/configstore/bower-github.json 
-rwxrwxrwx  1 zervis  staff  2 Sep  5 16:45 /Users/zervis/.config/configstore/bower-github.json
```
Hi @MatheusVellone , this is the output. As you can see, I intentionally give access to this file to all users, but still, I get this access deny error.

**Comment by darbio** [comment]
I have the same issue:

`-rw-------  1 darbio  staff  2  8 Feb  2017 /Users/darbio/.config/configstore/bower-github.json`

Blocks us from using this project.

**Comment by MatheusVellone** [comment]
It's a permission error, not directly related to `dynamodb-admin`.
I'm out of options of what to do to solve.

@darbio, have you tried commands described in bower/bower#2262 ?

**Comment by tierra** [comment]
This is actually a problem for the https://github.com/instructure/dynamo-local-admin-docker project as well, which has resorted to pinning back to 1.12.0 in the mean time.

**Comment by aaronshaf** [comment]
Bower usage now removed from the lib.

**Comment by tareq89** [comment]
Thank you very much @aaronshaf , it is working now!
