### ISSUE TITLE
Getting an error on 3.0.1

### ISSUE THREAD

**Issue by yoavain-sundaysky** [aaronshaf/dynamodb-admin#60]
Running on Windows 10.
Node version: 8.12.0
Dynamodb is running on http://localhost:8000
dynamodb-admin version: 3.0.1

Running dynamodb-admin result with the error:
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at exports.createServer (C:\Users\xxxxxxxx\AppData\Roaming\npm\node_modules\dynamodb-admin\lib\backend.js:98:28)
    at Object.<anonymous> (C:\Users\xxxxxxxx\AppData\Roaming\npm\node_modules\dynamodb-admin\bin\dynamodb-admin.js:33:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by rchl** [comment]
Version 3.0.2 should fix it. Sorry about the trouble.

**Comment by yoavain-sundaysky** [comment]
Thanks @rchl. 
Works great now!
Much smoother than 2.x
