### ISSUE TITLE
Cannot Purge when AttributeName contains hyphen

### ISSUE THREAD

**Issue by jvtrigueros** [aaronshaf/dynamodb-admin#75]
I'm getting this message:
```
{ ValidationException: Invalid ProjectionExpression: Syntax error; token: "-", near: "dummy-id"
    at Request.extractError (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/me/.npm/_npx/87829/lib/node_modules/dynamodb-admin/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'Invalid ProjectionExpression: Syntax error; token: "-", near: "dummy-id"',
  code: 'ValidationException',
  time: 2019-04-11T20:58:56.048Z,
  requestId: '913a0d7b-cdd9-42e6-8b98-866894f156e2',
  statusCode: 400,
  retryable: false,
  retryDelay: 11.40472097566253 }
```

**Comment by rchl** [comment]
Fixed in 3.1.3. Thanks for reporting.
